name: Build, Lint, Test & Deploy Frontend

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      REGISTRY_LOGIN_SERVER: plataforma-frontend-app.azurecr.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1) Instalamos pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 2) Cacheamos el store de pnpm
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # 3) Setup Node.js SIN cache automático
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
        run: pnpm install

      # 4) Instalo las dependencias usando el store cacheado
      - name: Install dependencies
        run: pnpm install --store ~/.pnpm-store

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

  deploy:
    if: github.event_name == 'push'
    needs: ci
    env:
      REGISTRY_LOGIN_SERVER: plataforma-frontend-app.azurecr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY_LOGIN_SERVER }}/plataforma-frontend:${{ github.sha }}
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: plataforma-frontend-app
          images: ${{ env.REGISTRY_LOGIN_SERVER }}/plataforma-frontend:${{ github.sha }}